# Generated by Django 5.2.3 on 2025-06-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='email',
            field=models.EmailField(default='no-email@example.com', help_text='請輸入您的電子郵件地址', max_length=254, verbose_name='電子郵件'),
            preserve_default=False,
        ),
    ]
