# Generated by Django 5.2.3 on 2025-06-22 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_recommended',
            field=models.BooleanField(default=False, verbose_name='推薦商品 (顯示於首頁)'),
        ),
    ]
