# Generated by Django 5.2.3 on 2025-06-24 01:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0002_item_is_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='創建時間'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
        migrations.AddField(
            model_name='rental',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='手機號碼'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('camera', '相機'), ('lens', '鏡頭'), ('accessory', '配件'), ('drone', '空拍機'), ('lighting', '燈光設備')], default='camera', max_length=50, verbose_name='品項類別'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price_per_day',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='每日租金'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='rental_app.item', verbose_name='租賃商品'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('pending', '待確認'), ('approved', '已確認'), ('returned', '已歸還'), ('cancelled', '已取消')], default='pending', max_length=10, verbose_name='租賃狀態'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='總租金'),
        ),
    ]
