# Generated by Django 5.2.3 on 2025-06-24 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0003_item_created_at_item_updated_at_rental_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='deposit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='商品押金'),
        ),
    ]
