# Generated by Django 5.2.3 on 2025-06-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0004_item_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('camera', '相機'), ('lens', '鏡頭'), ('other', '其他')], default='camera', max_length=50, verbose_name='品項類別'),
        ),
    ]
